### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ghost** [powercord-community/badges-everywhere#9]
![image](https://user-images.githubusercontent.com/81083382/116506728-23095980-a8be-11eb-8912-ef59b908ee90.png)

**Comment by cyyynthia** [comment]
Can't reproduce. Does the bug still happen after a reload?

**Comment by ghost** [comment]
> Can't reproduce. Does the bug still happen after a reload?

Yes

**Comment by realumbra** [comment]
same problem is happening to me

**Comment by ghost** [comment]
Same here

**Comment by cafeed28** [comment]
almost same, still happen after reload
![image](https://user-images.githubusercontent.com/62172116/123585331-79cadb00-d7fc-11eb-9909-6c434950bd9a.png)
